version: "3.4"
networks:
  kebab_network: {}
volumes:
  sqluser:
    external: true
  sqlsystem:
    external: true
  postgres:
    external: true
services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    container_name: autoheal
    environment:
    - "AUTOHEAL_CONTAINER_LABEL=all"
    volumes: 
    - "/var/run/docker.sock:/var/run/docker.sock"
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks: 
      - kebab_network
    environment:
    - "RABBITMQ_DEFAULT_PASS=password" 
    - "RABBITMQ_DEFAULT_USER=user"
    ports:
      - 15672:15672
      - 5672:5672
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "sql"
    networks: 
    - "kebab_network"
    ports:
    - 1433:1433
    environment:
    - "ACCEPT_EULA=Y"
    - "SA_PASSWORD=Tw0j4STARA!"
    volumes:
      - sqluser:/var/opt/sqlserver
      - sqlsystem:/var/opt/mssql
  postgres:
    container_name: "postgres"
    image: "postgres"
    ports:
    - 5432:5432
    networks: 
    - "kebab_network"
    environment: 
    - "POSTGRES_PASSWORD=password"
  menu:
    container_name: menu
    restart: always
    build: KebabMenuApplication/KebabMenuApplication
    ports:
    - 5001:80
    networks: 
    - "kebab_network"
    environment:
    - "ConnectionStrings__MenuDb=Server=sql, 1433;Database=MenuDB;User Id=sa;Password=Tw0j4STARA!;Encrypt=false;"
    - "ConnectionStrings__MasterDb=Server=sql, 1433;Database=master;User Id=sa;Password=Tw0j4STARA!;Encrypt=false;"
    - "RabbitMq__HostName=rabbitmq"
    - "RabbitMq__UserName=user"
    - "RabbitMq__Password=password"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s
  order:
    container_name: orders
    restart: always
    build: KebabOrderApplication/KebabOrderApplication
    ports:
    - 5002:80
    networks: 
    - "kebab_network"
    environment:
    - "ConnectionStrings__OrderDb=User Id=postgres;Password=password;Host=postgres;Port=5432;Database=OrdersDb;"
    - "ConnectionStrings__MasterDb=User Id=postgres;Password=password;Host=postgres;Port=5432;"
    - "RabbitMq__HostName=rabbitmq"
    - "RabbitMq__UserName=user"
    - "RabbitMq__Password=password"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s
