IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Menu' AND type='U')
BEGIN
CREATE TABLE Menu
(
    MenuId UNIQUEIDENTIFIER PRIMARY KEY,
    CreationDate DATETIME2,
);
END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'MenuItem' AND type='U')
BEGIN
CREATE TABLE MenuItem
(
    MenuItemId UNIQUEIDENTIFIER PRIMARY KEY,
    MenuId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Menu(MenuId) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Price DECIMAL NOT NULL
);
END;


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'ActiveMenu' AND type='U')
BEGIN
CREATE TABLE ActiveMenu
(
    CreationDate DATETIME2 PRIMARY KEY,
    MenuId UNIQUEIDENTIFIER NOT NULL,
    IsNewest BIT NOT NULL
);
END;

DECLARE @menuId UNIQUEIDENTIFIER = NEWID();
IF  ((SELECT COUNT(*) FROM Menu) < 1)
BEGIN
INSERT INTO Menu VALUES (@menuId, SYSDATETIME());
INSERT INTO MenuItem VALUES(NEWID(), @menuId, 'Some kebab', 20.00);
INSERT INTO ActiveMenu VALUES (SYSDATETIME(), @menuId, 1);
END;